### ISSUE TITLE
Foreign key constraint violation

### ISSUE THREAD

**Issue by dorians** [Cryptonomic/Conseil#539]
On a fresh master I get the following error while indexing against mainnet:

```
10:53:34.105 [lorre-system-akka.actor.default-dispatcher-27] ERROR tech.cryptonomic.conseil.Lorre$      - I failed to fetch delegates from client and update them
java.sql.BatchUpdateException: Batch entry 6 insert into "delegated_contracts" ("account_id","delegate_value")  values ('KT1Fb6tgR6Sq2SXu1XXHd9xub2ho4Wsb3Nqz','tz1iZEKy4LaAjnTmn2RuGDf2iqdAQKnRi8kY'),('KT1Fb83uSRQJR8YoTszAhjHGv1AREvehQ8cU','tz1Lhf4J9Qxoe3DZ2nfe8FGDnvVj7oKjnMY6'),('KT1FbBQ1k5XSxQWwCtUiZjTY9sCBTwF9ESuC','tz1Lhf4J9Qxoe3DZ2nfe8FGDnvVj7oKjnMY6'),('KT1Fbo3jWTGEZkhYF97qVrgGGDkjuuNXTZRg','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1Fbx4mizhvuVtrQSPu89qs7MXR2Y6cn6Uw','tz1bHzftcTKZMTZgLLtnrXydCm6UEqf4ivca'),('KT1Fc2Qzv2TtZeju5GdK5a3EGnJsdaGjf64B','tz1iZEKy4LaAjnTmn2RuGDf2iqdAQKnRi8kY'),('KT1Fd17ajP529Bb19KkttGjBPyAFZfR9PHGg','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1Fd2zF3nQYz3ZLbw7xDZqAAEjQszd7wacq','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1FdFfDPYB1RvgLpMNMTFsdknk5itDxFz5R','tz1ZTG13gkvouxSANka3HG3uys8C5gu3DPXZ'),('KT1Fdp1a7g8wSBUavu9dYuhneQRJFKoCrxzf','tz1bHzftcTKZMTZgLLtnrXydCm6UEqf4ivca'),('KT1FdvUmPAKkKWyLrpyuwMvcVof8Yr7Dxt8q','tz1Tnjaxk6tbAeC2TmMApPh8UsrEVQvhHvx5'),('KT1Fe9Wy35wmBPCdU3kuqFdmUfNKxad7wWZJ','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1FenCM2848CGvzKhim8vQSbYS72FT9Pj37','tz1iZEKy4LaAjnTmn2RuGDf2iqdAQKnRi8kY'),('KT1FizpHN5YvdaXWyZMgsgUcHe5Fd1pmGxQX','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1FjWsK3U9qd9QZCkfzUFfWkHGaSwbnAuFz','tz1WCd2jm4uSt4vntk4vSuUWoZQGhLcDuR9q'),('KT1FjYkVRghgC5HtTYeWjkkghBuSo54dTPeZ','tz1bsDft8TyJefdVowBd5jxCdiLhQF9owmpG'),('KT1Fk3ZCHejdYTckGeSKo8dPzJHCevF38Ho5','tz1WBRjFFTUYWcHTUrxJyiMRQtxYBkLotm8s'),('KT1Fk9QZvSjreRBs6Xvps3t1WZBnxq7ptBZy','tz1LesY3S4wfe15SNm1W3qJmQzWxLqVjTruH'),('KT1FkBEghBHixZ34HDX7sU4F5ifnMb5BkGQk','tz1iLbZZ9uoRuVJCrZ9ZwiJMpfzhy3c67mav'),('KT1FkhS799EeB2U27HuuotjM3Fv5GA42PSmZ','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1FkvbALTi3RU8Yt7hXgdGEGWw1JYEMDbka','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1Fm2gGTkeWneLq5PkTq58JMXppYuod58Eu','tz1LesY3S4wfe15SNm1W3qJmQzWxLqVjTruH'),('KT1Fm5sDsC7YPP1Lk1CkKoH8fL2ceRQJAXfX','tz1iZEKy4LaAjnTmn2RuGDf2iqdAQKnRi8kY'),('KT1FpFLreYXDRTcMdnBrF7jS24pp43AshXKp','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1FpSty5aJamtnSF7RwrPba7psNK3xgPUqv','tz1iZEKy4LaAjnTmn2RuGDf2iqdAQKnRi8kY'),('KT1FprQSqbY3Zgd4wYchxT1X1GtiDv9SJHsz','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1Fq7wU3XGuxHRdFp9Py73orhyGFqVvpi7H','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1FqipYGfg9VCT6j8veiN7GCHyHBwR4yWX5','tz1PXZjHzSdp9bMg7qMKVR9dh5qo1pwqJ2nd'),('KT1Fqncr7toViTqCkyjCvwLG78WNHvSVLSkV','tz1LLNkQK4UQV6QcFShiXJ2vT2ELw449MzAA'),('KT1FqsW9FSXR9fc8ibgqBbYVWXv3ipPCh4VQ','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1FrNBCACpFpS7bXpq4FrA1Mkd9HNZXBJVV','tz1hThMBD8jQjFt78heuCnKxJnJtQo9Ao25X'),('KT1FrgxGBPuB9C8krng56yJwBi4ope2vre8r','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1FsdqUQtayFWLtKb9ZAxMDT6xdFNkxejxA','tz1Tnjaxk6tbAeC2TmMApPh8UsrEVQvhHvx5'),('KT1FsiQx7A3zHo6cnecarXbwp2s86yFKo8p5','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1Fsp9uwxwAsW3sXRQBvTNHcnimmDBNzZGC','tz1iZEKy4LaAjnTmn2RuGDf2iqdAQKnRi8kY'),('KT1Ft4nur1od7AFnWUnBVt6spHDUNgzshZDT','tz1iDu3tHhf7H4jyXk6rGV4FNUsMqQmRkwLp'),('KT1Ft7Djd67RxYtp35T97m9TurBJ17PCZs8x','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1FtVzXWnSrNjeHUApL3nSGWFesUJRL454f','tz1cX93Q3KsiTADpCC4f12TBvAmS5tw7CW19'),('KT1FuFDZGdw86p6krdBUKoZfEMkcUmezqX5o','tz3RB4aoyjov4KEVRbuhvQ1CKJgBJMWhaeB8'),('KT1FugGEKncBV2rZJBJEoJGceR3ro39ttHcq','tz1h73i4WseQQxGa127BaLLSDzFuvxD8qiez'),('KT1FvEy5DtYURWE8sDLoC99zLDcifk5itpq2','tz1iZEKy4LaAjnTmn2RuGDf2iqdAQKnRi8kY'),('KT1FvroNQDTDeJEPq5naxkg315BbLyjKLYYb','tz1LesY3S4wfe15SNm1W3qJmQzWxLqVjTruH'),('KT1FwnvhJ5o8HeTma6mTGPMnJSAPnL1f2BPQ','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1Fx4McbkgrUERALvHEjdqR8w4SEtkjeLKB','tz1iDu3tHhf7H4jyXk6rGV4FNUsMqQmRkwLp'),('KT1FxLiUxn4GS1vMaKbosStbeqKjRzbPyFCD','tz1Tnjaxk6tbAeC2TmMApPh8UsrEVQvhHvx5'),('KT1FxUtk1SdNHAf6d6KkRuHVnPRojo8vX6Xr','tz1iLbZZ9uoRuVJCrZ9ZwiJMpfzhy3c67mav'),('KT1FxfQdB41PFAKjtNYqKgsYn8dA3qf7epqg','tz1LLNkQK4UQV6QcFShiXJ2vT2ELw449MzAA'),('KT1FxwsxsyAj5v4ZDN4gVEJ2WoLWUXFUmTzu','tz1Tnjaxk6tbAeC2TmMApPh8UsrEVQvhHvx5'),('KT1FyAAVqi2yrVdjBmnX92XKywHT6Bg8JEjD','tz1Tnjaxk6tbAeC2TmMApPh8UsrEVQvhHvx5'),('KT1FyS8mKWb9MrFVaYmKDjvdBBDs6biAbXRu','tz1LLNkQK4UQV6QcFShiXJ2vT2ELw449MzAA'),('KT1Fyvy6zY4oXyBcskbsWjSEg8Xs9j53peEg','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1G1ARHx4Ujry8PzTis6HLNwQ29rYQY2Nay','tz1bHzftcTKZMTZgLLtnrXydCm6UEqf4ivca'),('KT1G1E68VkbYHDZMapSUh7eDW9bUruzRSRM9','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1G1hASMUS6aKAKgVbM6k9V1UfUCufb9TDk','tz1SUgyRB8T5jXgXAwS33pgRHAKrafyg87Yc'),('KT1G24X9Ve2BfqwAy2HxRvKJkt6zkqsPa5oi','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1G2cc94ebQ5hWZ8swAEEc49L3aCT5ZLXtU','tz1Tnjaxk6tbAeC2TmMApPh8UsrEVQvhHvx5'),('KT1G2tZ4S2QuXKm3CkJkbqwuvn9Sp45Vi31b','tz1NpWrAyDL9k2Lmnyxcgr9xuJakbBxdq7FB'),('KT1G2u3hP9JPsk6ezn2YYgeHqKFkGMuRxu3B','tz1Tnjaxk6tbAeC2TmMApPh8UsrEVQvhHvx5'),('KT1G3A8EdHW3sfk3nML7Bb7RQF3q5gZQpbhu','tz1LLNkQK4UQV6QcFShiXJ2vT2ELw449MzAA'),('KT1G48dcsEKRZxnMRx1wa7XWbutk3CJyvWYB','tz1eMKUnpTfS7ypTH9SRTRXBW4RBE8EEszsD'),('KT1G6RFHptDKqZ45gRCSuX2dyCmu6jgo2SNu','tz1LesY3S4wfe15SNm1W3qJmQzWxLqVjTruH'),('KT1G6fh4PbKrLt1X8xLLJZQXH57vWBzqNE2g','tz1bHzftcTKZMTZgLLtnrXydCm6UEqf4ivca'),('KT1G6nL82hYCcy58DgdW1ZtvDyMMU1ZKJ6JE','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1G6pFu63PGRgKzoA1ZAj8bkJ6dq1ohzK2q','tz1iZEKy4LaAjnTmn2RuGDf2iqdAQKnRi8kY'),('KT1G71XZbCtNEwvmcqtHh9gzYL5po2gSH3tV','tz1cX93Q3KsiTADpCC4f12TBvAmS5tw7CW19'),('KT1G8q6TVqbAA96aoy2WzE1HukDPdEqMS2r8','tz3bEQoFCZEEfZMskefZ8q8e4eiHH1pssRax'),('KT1GApGtUELTERixFef4Db9WjviDs3wuRp8V','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1GBWz8miqvHz6MxJ8C98GzhYDvJJoiU8TM','tz1Tnjaxk6tbAeC2TmMApPh8UsrEVQvhHvx5'),('KT1GBwCXwLvZuAhuQcpEtAhKs288jXX6uzVB','tz1WN99fToybHVrkx5Kd9WL8ECVGtfhHMytQ'),('KT1GCwrytyvsQmHvcJwaUu7t8K9xtift8DVE','tz1iDu3tHhf7H4jyXk6rGV4FNUsMqQmRkwLp'),('KT1GDA7DDsfRedcQ7ExAjKo6PaGQaNZPy38y','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1GDCrDVRMBR2ZeXCJQ6HpC3qt14v6ECqGp','tz1Tnjaxk6tbAeC2TmMApPh8UsrEVQvhHvx5'),('KT1GEdM2qaLwbrrW8syHU66ZU88wR3sDj8sw','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1GFZKQGUyX73SdWS2Y2u4n6uvpNAQBGt4i','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1GGzww5h1bwtz28Fw6sfgX7ZB5KfBiVNth','tz1Tnjaxk6tbAeC2TmMApPh8UsrEVQvhHvx5'),('KT1GHDMz4bY7AhjopX7JghRpXf19U2MeM5ky','tz1LesY3S4wfe15SNm1W3qJmQzWxLqVjTruH'),('KT1GHV4H16SLo5BMLaQ7YnuSCM6JppRVpDiL','tz3bEQoFCZEEfZMskefZ8q8e4eiHH1pssRax'),('KT1GHXvnHReiGTsWEAPbo4itFV7sQ4THWPDj','tz1LLNkQK4UQV6QcFShiXJ2vT2ELw449MzAA'),('KT1GHiUzp4rb8KbP9XCC27v9mGRBFcaLyeB3','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1GHkFECRfyZXE3Yc3Us2SqhdCVXkdrFVFH','tz1bHzftcTKZMTZgLLtnrXydCm6UEqf4ivca'),('KT1GJ7aMzAPruWznKH1FDDRPd39YQhKNDMLC','tz1Tnjaxk6tbAeC2TmMApPh8UsrEVQvhHvx5'),('KT1GJcRMp1Lv6UZ5WdFZUc3TuNfHdYDKywR9','tz1WCd2jm4uSt4vntk4vSuUWoZQGhLcDuR9q'),('KT1GK2ThdRVS5nxtmXhNSt3hEUJwkNJyb1Vf','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1GKFssD7fw7QUWPatcEfpDxnsR2MCitdTf','tz1iLbZZ9uoRuVJCrZ9ZwiJMpfzhy3c67mav'),('KT1GKvp2wQFMKCH1UpHXy3WYg9pp1MEdLaMZ','tz1WCd2jm4uSt4vntk4vSuUWoZQGhLcDuR9q'),('KT1GL4mo3j9Gv5tpALvTVpEvZZv5te75EY33','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1GLftC6q47f78mK7ey6yztUNcM2xwZPbaE','tz1cX93Q3KsiTADpCC4f12TBvAmS5tw7CW19'),('KT1GMi5vmEqnvzFaMgUcGXcPQCMMyagjRkqE','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1GMi9HBwNQ4EHvwpLr35iXDRPhAfTmyyBQ','tz1LLNkQK4UQV6QcFShiXJ2vT2ELw449MzAA'),('KT1GMxdkfqgYecHWxRwXNJEB8FSF7th2rMpn','tz1QkfLMUh4bMngiJexAC44XpCuREAHT5azq'),('KT1GNbohPG7RDZ1izm1ixtawK19fWUBhKK3m','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1GPYiJh54Qsb32GBjDLUxj24ELSX53hERS','tz1Tnjaxk6tbAeC2TmMApPh8UsrEVQvhHvx5'),('KT1GPqxeHd37YDVzX6xN2CbBrymhx9sh6ZbH','tz1eewjYhPoR4o1x9pWgNtCU1GUAkp9Qb76q'),('KT1GPuxLLXsZauYpvErdQrZyU8NJNXtitqzP','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1GQ8uvASkL4GMmNGS5xmATxrwrZZT18W1w','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1GQF9Zj7pztM29eJTt3EJAHe6NbECJkvzk','tz1LesY3S4wfe15SNm1W3qJmQzWxLqVjTruH'),('KT1GQK6TFhdrmK5jwjR1JfURHopUnaj6LW1n','tz1TcH4Nb3aHNDJ7CGZhU7jgAK1BkSP4Lxds'),('KT1GQNC5BezYwEkpe1PNeZkp9DT2eyDwUyoS','tz1bHzftcTKZMTZgLLtnrXydCm6UEqf4ivca'),('KT1GRCnXtxKrmpXyALGUKz5Kc7ijBoS9iKHu','tz1aRhFErGMgL57DYHMT1vYwv7PzsJN1chrk'),('KT1GS2TLBGBkMgeybpTZ1MPN1W29rXcMXm6T','tz1iZEKy4LaAjnTmn2RuGDf2iqdAQKnRi8kY'),('KT1GSvfmH7nPSRLAF6MTNzALzCnvQ3gDENN9','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1GT4uGKjWeoGwGundjthif8ekyGhWX9ZBW','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1GTWNTdBGkCqCkrErc3EYsafuD3KEnonWC','tz1Tnjaxk6tbAeC2TmMApPh8UsrEVQvhHvx5'),('KT1GUHU4jFLcbDz6iAn61Ru2cmZWFPMnz35c','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1GULRGqcFERgQQta3cpNfetxShXomQCWpt','tz1bHzftcTKZMTZgLLtnrXydCm6UEqf4ivca'),('KT1GUUhDSVGLpkepfCwgPRt98TpiYbTDN55L','tz1WCd2jm4uSt4vntk4vSuUWoZQGhLcDuR9q'),('KT1GUXLA3hiMZgMvZ8vEh5ewybyReexh1mfg','tz1LLNkQK4UQV6QcFShiXJ2vT2ELw449MzAA'),('KT1GUXaXY9qd56iAhauQD67CpYL4se9DchGs','tz1hThMBD8jQjFt78heuCnKxJnJtQo9Ao25X'),('KT1GVZFbCjm4vKmgQhR7pg4jjUuxEMR9BZTU','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1GVmcdShSehDRJNVfaQkJTQSeEnzVMktcs','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1GVrin3BLyAtHMNKQPfCAnkZtbLLnsUFSy','tz1Tnjaxk6tbAeC2TmMApPh8UsrEVQvhHvx5'),('KT1GVwXUpQt349HM69CtCbXo7wW2j9rFtxdm','tz1LLNkQK4UQV6QcFShiXJ2vT2ELw449MzAA'),('KT1GWRYLj6WuuJgGmFUpH8VAZwzMuTRfAyPt','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1GWqSNvFXzH38EpQD9YrcmgiTZmo1XhKJQ','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1GY7CQGNEFwgEAQ9yoWq815oRieAVRvdg3','tz1bHzftcTKZMTZgLLtnrXydCm6UEqf4ivca'),('KT1GYpwhPW93z2dBBThF2wkVPtUUSaaayiGr','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1GZ8Wd7eq1UdM6BN66NH5aw1W8WdZEn9VD','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1GZGdspwCecUGR5uPQbpcFgUVhAzizEdNw','tz1NortRftucvAkD1J58L32EhSVrQEWJCEnB'),('KT1Gb1QFMpViv1AmhQX9HTsLVdaraQDumPoW','tz1hThMBD8jQjFt78heuCnKxJnJtQo9Ao25X'),('KT1Gb7yyTEEsjzVUdJjq91bGeKzkA7WdozBC','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1Gb8u9Q4ypemH3ZtKMSzY39vMrdWU8UQvP','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1GbVHbEXqEnu18FaobkExQgAJbUfoWbcWR','tz1S7GgVV4FPEGUVzepKBwx22DyNikdpa4X6'),('KT1GcSsQaTtMB2HvUKU9b6WRFUnGpGx9JwGk','tz1SUgyRB8T5jXgXAwS33pgRHAKrafyg87Yc'),('KT1GcT65fuvjsZoV2iWVewiXgtSiyDQNjF7m','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1GcWhnAnaDqGP9u5kjgywUwyoPrX2WX2RN','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1GccBba1fKtWguXj9mEAJZVxsMa7YiT7vM','tz1iZEKy4LaAjnTmn2RuGDf2iqdAQKnRi8kY'),('KT1GcfbYQ1nedpE1KhaWLqdL83jeD2YjDZfd','tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ'),('KT1GcqaAP5aCz4wPmhPmNztsgna98QVw6L3p','tz1eewjYhPoR4o1x9pWgNtCU1GUAkp9Qb76q') was aborted: ERROR: insert or update on table "delegated_contracts" violates foreign key constraint "contracts_delegate_pkh_fkey"
  Detail: Key (delegate_value)=(tz1WBRjFFTUYWcHTUrxJyiMRQtxYBkLotm8s) is not present in table "delegates".  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2191)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:472)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:791)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1563)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$18(JdbcActionComponent.scala:544)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:513)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:538)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:30)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:27)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:275)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:275)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: ERROR: insert or update on table "delegated_contracts" violates foreign key constraint "contracts_delegate_pkh_fkey"
  Detail: Key (delegate_value)=(tz1WBRjFFTUYWcHTUrxJyiMRQtxYBkLotm8s) is not present in table "delegates".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
	... 18 common frames omitted
```

**Comment by ba205** [comment]
Currently hard to reproduce.
