### ISSUE TITLE
Fail to fetch block from tezos node. 

### ISSUE THREAD

**Issue by MegaSolar** [Cryptonomic/Conseil#712]
Helllo. 
I have started to fetch block through conseil local deployment, But I have stuck to get error like below error. 
Someone give me advice would be so much appreciated. 

```
java -Dconfig.file=/home/docker/tezos/Conseil/reference.conf -cp /tmp/conseil.jar tech.cryptonomic.conseil.Lorre --headHash BLV7VatCp26Mr2MkoFGFFxKFPGrUdhdhQ9TXrFNSSTiskYgBR21 --depth all --verbose mainnet
15:18:17.532 [main] ERROR                                          tech.cryptonomic.conseil.Lorre$      - Error while reading registered tokens file: '' is not a valid Int
15:18:17.628 [main] INFO                                           com.zaxxer.hikari.HikariDataSource   - lorre.db - Starting...
15:18:17.655 [main] INFO                                           com.zaxxer.hikari.HikariDataSource   - lorre.db - Start completed.
15:18:17.680 [main] INFO                                           t.c.c.t.TezosDatabaseOperations$CustomPostgresProfile -  >>> binding uuid -> java.util.UUID 
15:18:17.680 [main] INFO                                           t.c.c.t.TezosDatabaseOperations$CustomPostgresProfile -  >>> binding text -> java.lang.String 
15:18:17.680 [main] INFO                                           t.c.c.t.TezosDatabaseOperations$CustomPostgresProfile -  >>> binding bool -> Boolean 
15:18:18.038 [main] INFO                                           tech.cryptonomic.conseil.Lorre$      - 
 ==================================***==================================
  Lorre v.0.2010.0020-SNAPSHOT
  [commit-hash: 4b69b8d]
 ==================================***==================================

  About to start processing data on the mainnet network


15:18:18.044 [main] INFO                                           tech.cryptonomic.conseil.Lorre$      - 
 ==================================***==================================
 Configuration details

 Connecting to tezos mainnet
 on node http://192.168.56.103:8732//main

 Reference hash for synchronization with the chain: BLV7VatCp26Mr2MkoFGFFxKFPGrUdhdhQ9TXrFNSSTiskYgBR21
 Requested depth of synchronization: Everything
 Environment set to skip failed download of chain data: yes [†]

 Database configuration:

 - password = ******
 - maxConnections = 64
 - dataSourceClass = "org.postgresql.ds.PGSimpleDataSource"
 - properties.databaseName = "conseil"
 - properties.user = "postgres"
 - numThreads = 64
 - properties.reWriteBatchedInserts = true


 [†] To let the process crash on error,
     set an environment variable named LORRE_FAILURE_IGNORE to "off" or "no"
 ==================================***==================================

      
15:18:18.082 [lorre-system-akka.actor.default-dispatcher-2] INFO   tech.cryptonomic.conseil.Lorre$      - Written 1 registered token rows
15:18:19.074 [main] INFO                                           tech.cryptonomic.conseil.Lorre$      - Successfully made initial connection to Tezos
15:18:19.080 [lorre-system-akka.actor.default-dispatcher-4] INFO   tech.cryptonomic.conseil.Lorre$      - Processing Tezos Blocks..
15:18:19.640 [lorre-system-akka.actor.default-dispatcher-3] INFO   t.c.conseil.tezos.TezosNodeOperator  - Fetching block data in range: Range 1 to 50
15:18:19.679 [lorre-system-akka.actor.default-dispatcher-4] INFO   t.c.conseil.tezos.TezosNodeOperator  - Fetching blocks for offsets 858917 to 858966
15:18:20.430 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.431 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.431 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.431 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.431 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.431 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.431 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.431 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.431 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.431 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.431 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.431 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.431 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.431 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.431 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.432 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.432 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.432 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.432 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.432 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.432 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.432 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.432 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.432 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.432 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.432 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.432 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.432 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.432 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.432 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.432 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.433 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.433 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.433 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.433 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.433 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.433 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.433 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.433 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.433 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.433 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.433 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.433 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.433 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.433 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.433 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.433 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.433 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.433 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.433 [lorre-system-akka.actor.default-dispatcher-30] ERROR t.c.conseil.tezos.TezosNodeOperator  - I fetched a block definition from tezos node that I'm unable to decode: 
io.circe.ParsingFailure: exhausted input
15:18:20.443 [lorre-system-akka.actor.default-dispatcher-17] ERROR tech.cryptonomic.conseil.Lorre$      - Could not fetch blocks from client
io.circe.ParsingFailure: exhausted input
15:18:20.443 [main] INFO                                           tech.cryptonomic.conseil.Lorre$      - Doing clean-up
15:18:20.445 [main] INFO                                           com.zaxxer.hikari.HikariDataSource   - lorre.db - Shutdown initiated...
15:18:20.457 [main] INFO                                           com.zaxxer.hikari.HikariDataSource   - lorre.db - Shutdown completed.
[ERROR] [03/10/2020 15:18:20.533] [lorre-system-akka.actor.default-dispatcher-29] [akka.actor.ActorSystemImpl(lorre-system)] exception while executing timer task
java.lang.IllegalStateException: cannot create children while terminating or terminated
	at akka.actor.dungeon.Children.makeChild(Children.scala:273)
	at akka.actor.dungeon.Children.attachChild(Children.scala:49)
	at akka.actor.dungeon.Children.attachChild$(Children.scala:48)
	at akka.actor.ActorCell.attachChild(ActorCell.scala:429)
	at akka.actor.ActorSystemImpl.systemActorOf(ActorSystem.scala:750)
	at akka.stream.ActorMaterializer$.actorOfStreamSupervisor(ActorMaterializer.scala:73)
	at akka.stream.ActorMaterializer$.apply(ActorMaterializer.scala:65)
	at akka.stream.ActorMaterializer$.apply(ActorMaterializer.scala:42)
	at tech.cryptonomic.conseil.Lorre$.writeFutureRights(Lorre.scala:121)
	at tech.cryptonomic.conseil.Lorre$.$anonfun$new$3(Lorre.scala:112)
	at akka.actor.Scheduler$$anon$2.run(Scheduler.scala:102)
	at akka.actor.LightArrayRevolverScheduler$$anon$1$$anon$2.run(LightArrayRevolverScheduler.scala:101)
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.run(LightArrayRevolverScheduler.scala:337)
	at akka.actor.LightArrayRevolverScheduler.$anonfun$close$1(LightArrayRevolverScheduler.scala:141)
	at akka.actor.LightArrayRevolverScheduler.$anonfun$close$1$adapted(LightArrayRevolverScheduler.scala:140)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at akka.actor.LightArrayRevolverScheduler.close(LightArrayRevolverScheduler.scala:140)
	at akka.actor.ActorSystemImpl.stopScheduler(ActorSystem.scala:937)
	at akka.actor.ActorSystemImpl.$anonfun$_start$1(ActorSystem.scala:872)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at akka.actor.ActorSystemImpl$$anon$3.run(ActorSystem.scala:892)
	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$addRec$1$1.applyOrElse(ActorSystem.scala:1068)
	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$addRec$1$1.applyOrElse(ActorSystem.scala:1068)
	at scala.concurrent.Future.$anonfun$andThen$1(Future.scala:536)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Exception in thread "main" 15:18:20.539 [main] INFO                                           tech.cryptonomic.conseil.Lorre$      - All things closed
tech.cryptonomic.conseil.tezos.TezosErrors$BlocksProcessingFailed
	at tech.cryptonomic.conseil.Lorre$.$anonfun$processTezosBlocks$49(Lorre.scala:506)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
15:18:20.544 [shutdownHook1] INFO                                  tech.cryptonomic.conseil.Lorre$      - Doing clean-up
Exception in thread "shutdownHook1" java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:219)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
	at scala.concurrent.Await$.result(package.scala:146)
	at tech.cryptonomic.conseil.Lorre$.shutdown(Lorre.scala:173)
	at tech.cryptonomic.conseil.Lorre$.$anonfun$new$2(Lorre.scala:71)
	at scala.sys.ShutdownHookThread$$anon$1.run(ShutdownHookThread.scala:37)
```

postgresql-11 version :  11.7
sbt script version: 1.3.8
Java version : openjdk version "1.8.0_242"
Scala version : 2.12.8

**Comment by ivanopagano** [comment]
Hi, are you running a personal tezos node on a VPN?

I see you're connecting to `node http://192.168.56.103:8732//main`, where is that located wrt your Conseil instance?

I'm asking because I see no explicit reason for failure other than the fact that it looks like you're receiving empty responses from the node.

You might want to try and run curl for the 
`http://192.168.56.103:8732//main/` node, on some basic endpoint like `/blocks/head` and see if it can be reached from the Conseil host machine

**Comment by vishakh** [comment]
Closing as there was no follow up.
