### ISSUE TITLE
Suddenly conseil lorre process goes to exit. 

### ISSUE THREAD

**Issue by MegaSolar** [Cryptonomic/Conseil#713]
Please see log below

```
17:06:32.944 [lorre-system-akka.actor.default-dispatcher-19] INFO  t.c.conseil.tezos.TezosNodeOperator  - No new blocks to fetch from the network
17:06:32.945 [main] INFO                                           tech.cryptonomic.conseil.Lorre$      - Taking a nap
17:06:37.947 [lorre-system-akka.actor.default-dispatcher-31] INFO  tech.cryptonomic.conseil.Lorre$      - Processing Tezos Blocks..
17:06:38.040 [lorre-system-akka.actor.default-dispatcher-2] INFO   t.c.conseil.tezos.TezosNodeOperator  - No new blocks to fetch from the network
17:06:38.041 [main] INFO                                           tech.cryptonomic.conseil.Lorre$      - Taking a nap
17:06:43.042 [lorre-system-akka.actor.default-dispatcher-31] INFO  tech.cryptonomic.conseil.Lorre$      - Processing Tezos Blocks..
17:06:43.123 [lorre-system-akka.actor.default-dispatcher-16] INFO  t.c.conseil.tezos.TezosNodeOperator  - No new blocks to fetch from the network
17:06:43.124 [main] INFO                                           tech.cryptonomic.conseil.Lorre$      - Taking a nap
17:06:48.125 [lorre-system-akka.actor.default-dispatcher-22] INFO  tech.cryptonomic.conseil.Lorre$      - Processing Tezos Blocks..
17:06:48.201 [lorre-system-akka.actor.default-dispatcher-3] INFO   t.c.conseil.tezos.TezosNodeOperator  - I found the new block head at level 859073, the currently stored max is 859072. I'll fetch the missing 1 blocks.
17:06:48.202 [lorre-system-akka.actor.default-dispatcher-2] INFO   t.c.conseil.tezos.TezosNodeOperator  - Fetching block data in range: Range 859073 to 859073
17:06:48.202 [lorre-system-akka.actor.default-dispatcher-2] INFO   t.c.conseil.tezos.TezosNodeOperator  - Fetching blocks for offsets 0 to 0 
17:06:48.222 [lorre-system-akka.actor.default-dispatcher-2] INFO   t.c.conseil.tezos.TezosNodeOperator  - Fetching operations
17:06:48.240 [lorre-system-akka.actor.default-dispatcher-2] INFO   t.c.conseil.tezos.TezosNodeOperator  - Fetching current quorum
17:06:48.240 [lorre-system-akka.actor.default-dispatcher-2] INFO   t.c.conseil.tezos.TezosNodeOperator  - Fetching current proposal
17:06:48.245 [lorre-system-akka.actor.default-dispatcher-27] INFO  t.c.c.tezos.TezosDatabaseOperations$ - Writing blocks and account checkpoints to the DB...
17:06:48.245 [lorre-system-akka.actor.default-dispatcher-27] INFO  t.c.c.tezos.TezosDatabaseOperations$ - Writing 1 block records to DB...
17:06:48.247 [lorre-system-akka.actor.default-dispatcher-27] INFO  t.c.c.tezos.TezosDatabaseOperations$ - Writing 27 account checkpoints to DB...
17:06:48.317 [lorre-system-akka.actor.default-dispatcher-27] INFO  tech.cryptonomic.conseil.Lorre$      - Wrote 1 blocks to the database, checkpoint stored for account updates
17:06:48.317 [lorre-system-akka.actor.default-dispatcher-27] INFO  tech.cryptonomic.conseil.Lorre$      - Processing latest Tezos data for updated accounts...
17:06:48.317 [lorre-system-akka.actor.default-dispatcher-27] INFO  tech.cryptonomic.conseil.Lorre$      - Ready to fetch updated accounts information from the chain
17:06:48.318 [lorre-system-akka.actor.default-dispatcher-20] INFO  t.c.conseil.tezos.TezosNodeOperator  - Fetching accounts for block BLGKKX6ruC8GHGYrRb2UC3dbX4B216VPxBMXMsys3uCDzfwkcWZ
17:06:48.369 [lorre-system-akka.actor.default-dispatcher-26] INFO  t.c.c.tezos.TezosDatabaseOperations$ - Writing accounts and delegate checkpoints to the DB...
17:06:48.369 [lorre-system-akka.actor.default-dispatcher-26] INFO  t.c.c.tezos.TezosDatabaseOperations$ - Writing 1 accounts to DB...
17:06:48.371 [lorre-system-akka.actor.default-dispatcher-26] INFO  t.c.c.tezos.TezosDatabaseOperations$ - Writing 1 accounts_history to DB...
17:06:48.375 [lorre-system-akka.actor.default-dispatcher-26] INFO  t.c.c.tezos.TezosDatabaseOperations$ - Writing 25 delegate checkpoints to DB...
17:06:48.398 [lorre-system-akka.actor.default-dispatcher-4] INFO   tech.cryptonomic.conseil.Lorre$      - 27 accounts were touched on the database. Checkpoint stored for delegates.
17:06:48.398 [lorre-system-akka.actor.default-dispatcher-4] INFO   tech.cryptonomic.conseil.Lorre$      - Cleaning 27 processed accounts from the checkpoint...
17:06:48.398 [lorre-system-akka.actor.default-dispatcher-4] INFO   t.c.c.tezos.TezosDatabaseOperations$ - Cleaning the accounts checkpoint table.. 
17:06:48.403 [lorre-system-akka.actor.default-dispatcher-4] INFO   tech.cryptonomic.conseil.Lorre$      - Done cleaning 27 accounts checkpoint rows.
17:06:48.403 [lorre-system-akka.actor.default-dispatcher-4] INFO   tech.cryptonomic.conseil.Lorre$      - Processing latest Tezos data for account delegates...
17:06:48.403 [lorre-system-akka.actor.default-dispatcher-4] INFO   tech.cryptonomic.conseil.Lorre$      - Ready to fetch updated delegates information from the chain
17:06:48.404 [lorre-system-akka.actor.default-dispatcher-4] INFO   t.c.conseil.tezos.TezosNodeOperator  - Fetching delegated contracts for block BLGKKX6ruC8GHGYrRb2UC3dbX4B216VPxBMXMsys3uCDzfwkcWZ
[WARN] [03/10/2020 17:06:56.421] [lorre-system-akka.actor.default-dispatcher-25] [lorre-system/Pool(shared->http://192.168.56.103:8732)] [14 (WaitingForResponseEntitySubscription)] Response entity was not subscribed after 5 seconds. Make sure to read the response entity body or call `discardBytes()` on it. GET /chains/main/blocks/BLGKKX6ruC8GHGYrRb2UC3dbX4B216VPxBMXMsys3uCDzfwkcWZ/context/delegates/tz1P2Po7YM526ughEsRbY4oR9zaUPDZjxFrb Empty -> 200 OK Default(31235 bytes)
17:06:56.789 [lorre-system-akka.actor.default-dispatcher-24] ERROR t.c.conseil.tezos.TezosNodeOperator  - I encountered problems while fetching delegates data from mainnet, for pkhs tz3UoffC7FG7zfpmvmjUmUeAaHvzdcUvAj6r, tz2TSvNTh2epDMhZHrw73nV9piBX7kLZ9K9m, tz1eEnQhbwf6trb8Q8mPb2RaPkNk2rN7BKi8, tz1TzaNn7wSQSP5gYPXCnNzBCpyMiidCq1PX, tz3VEZ4k6a4Wx42iyev6i2aVAptTRLEAivNN, tz1LmaFsWRkjr7QMCx5PtV6xTUz3AmEpKQiF, tz3NExpXn9aPNZPorRE4SdjJ2RGrfbJgMAaV, tz3WMqdzXqRWXwyvj5Hp2H7QEepaUuS7vd9K, tz1S8MNvuFEUsWgjHvi3AxibRBf388NhT1q2, tz3bTdwZinP8U1JmSweNzVKhmwafqWmFWRfk, tz1LLNkQK4UQV6QcFShiXJ2vT2ELw449MzAA, tz1irJKkXS2DBWkU1NnmFQx1c1L7pbGg4yhk, tz1TRqbYbUf2GyrjErf3hBzgBJPzW8y36qEs, tz1gfArv665EUkSg2ojMBzcbfwuPxAvqPvjo, tz1P2Po7YM526ughEsRbY4oR9zaUPDZjxFrb, tz3bvNMQ95vfAYtG8193ymshqjSvmxiCUuR5, tz1cX93Q3KsiTADpCC4f12TBvAmS5tw7CW19, tz1Ldzz6k1BHdhuKvAtMRX7h5kJSMHESMHLC, tz1NpWrAyDL9k2Lmnyxcgr9xuJakbBxdq7FB, tz1MecudVJnFZN5FSrriu8ULz2d6dDTR7KaM, tz3RDC3Jdn4j15J7bBHZd29EUee9gVB1CxD9, tz1V2FYediKBAEaTpXXJBSjuQpjkyCzrTSiE, tz1Kf25fX1VdmYGSEzwFy1wNmkbSEZ2V83sY, tz1MXFrtZoaXckE41bjUCSjAjAap3AFDSr3N, tz3RB4aoyjov4KEVRbuhvQ1CKJgBJMWhaeB8. The error says Substream Source cannot be materialized more than once
17:06:56.799 [lorre-system-akka.actor.default-dispatcher-24] ERROR t.c.conseil.tezos.TezosNodeOperator  - Could not get delegates' data for key hashes tz3UoffC7FG7zfpmvmjUmUeAaHvzdcUvAj6r,tz2TSvNTh2epDMhZHrw73nV9piBX7kLZ9K9m,tz1eEnQhbwf6trb8Q8mPb2RaPkNk2rN7BKi8,tz1TzaNn7wSQSP5gYPXCnNzBCpyMiidCq1PX,tz3VEZ4k6a4Wx42iyev6i2aVAptTRLEAivNN,tz1LmaFsWRkjr7QMCx5PtV6xTUz3AmEpKQiF,tz3NExpXn9aPNZPorRE4SdjJ2RGrfbJgMAaV,tz3WMqdzXqRWXwyvj5Hp2H7QEepaUuS7vd9K,tz1S8MNvuFEUsWgjHvi3AxibRBf388NhT1q2,tz3bTdwZinP8U1JmSweNzVKhmwafqWmFWRfk,tz1LLNkQK4UQV6QcFShiXJ2vT2ELw449MzAA,tz1irJKkXS2DBWkU1NnmFQx1c1L7pbGg4yhk,tz1TRqbYbUf2GyrjErf3hBzgBJPzW8y36qEs,tz1gfArv665EUkSg2ojMBzcbfwuPxAvqPvjo,tz1P2Po7YM526ughEsRbY4oR9zaUPDZjxFrb,tz3bvNMQ95vfAYtG8193ymshqjSvmxiCUuR5,tz1cX93Q3KsiTADpCC4f12TBvAmS5tw7CW19,tz1Ldzz6k1BHdhuKvAtMRX7h5kJSMHESMHLC,tz1NpWrAyDL9k2Lmnyxcgr9xuJakbBxdq7FB,tz1MecudVJnFZN5FSrriu8ULz2d6dDTR7KaM,tz3RDC3Jdn4j15J7bBHZd29EUee9gVB1CxD9,tz1V2FYediKBAEaTpXXJBSjuQpjkyCzrTSiE,tz1Kf25fX1VdmYGSEzwFy1wNmkbSEZ2V83sY,tz1MXFrtZoaXckE41bjUCSjAjAap3AFDSr3N,tz3RB4aoyjov4KEVRbuhvQ1CKJgBJMWhaeB8
java.lang.IllegalStateException: Substream Source cannot be materialized more than once
        at akka.stream.impl.fusing.SubSource$$anon$13.setCB(StreamOfStreams.scala:756)
        at akka.stream.impl.fusing.SubSource$$anon$13.preStart(StreamOfStreams.scala:766)
        at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:291)
        at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:557)
        at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:664)
        at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:712)
        at akka.actor.Actor.aroundPreStart(Actor.scala:528)
        at akka.actor.Actor.aroundPreStart$(Actor.scala:528)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:655)
        at akka.actor.ActorCell.create(ActorCell.scala:656)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:527)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:549)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:283)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
17:06:56.800 [lorre-system-akka.actor.default-dispatcher-22] ERROR tech.cryptonomic.conseil.Lorre$      - I failed to fetch delegates from client and update them
java.lang.IllegalStateException: Substream Source cannot be materialized more than once
        at akka.stream.impl.fusing.SubSource$$anon$13.setCB(StreamOfStreams.scala:756)
        at akka.stream.impl.fusing.SubSource$$anon$13.preStart(StreamOfStreams.scala:766)
        at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:291)
        at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:557)
        at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:664)
        at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:712)
        at akka.actor.Actor.aroundPreStart(Actor.scala:528)
        at akka.actor.Actor.aroundPreStart$(Actor.scala:528)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:655)
        at akka.actor.ActorCell.create(ActorCell.scala:656)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:527)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:549)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:283)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
17:06:56.801 [main] INFO                                           tech.cryptonomic.conseil.Lorre$      - Doing clean-up
17:06:56.808 [main] INFO                                           com.zaxxer.hikari.HikariDataSource   - lorre.db - Shutdown initiated...
17:06:56.848 [main] INFO                                           com.zaxxer.hikari.HikariDataSource   - lorre.db - Shutdown completed.
[WARN] [03/10/2020 17:06:56.851] [lorre-system-akka.actor.default-dispatcher-16] [lorre-system/Pool(shared->http://192.168.56.103:8732)] [2 (WaitingForResponseEntitySubscription)] Ongoing request [GET /chains/main/blocks/BLGKKX6ruC8GHGYrRb2UC3dbX4B216VPxBMXMsys3uCDzfwkcWZ/context/delegates/tz1eEnQhbwf6trb8Q8mPb2RaPkNk2rN7BKi8 Empty] was dropped because pool is shutting down
[WARN] [03/10/2020 17:06:56.851] [lorre-system-akka.actor.default-dispatcher-16] [lorre-system/Pool(shared->http://192.168.56.103:8732)] [3 (WaitingForResponseEntitySubscription)] Ongoing request [GET /chains/main/blocks/BLGKKX6ruC8GHGYrRb2UC3dbX4B216VPxBMXMsys3uCDzfwkcWZ/context/delegates/tz1TzaNn7wSQSP5gYPXCnNzBCpyMiidCq1PX Empty] was dropped because pool is shutting down
[WARN] [03/10/2020 17:06:56.851] [lorre-system-akka.actor.default-dispatcher-16] [lorre-system/Pool(shared->http://192.168.56.103:8732)] [5 (WaitingForResponseEntitySubscription)] Ongoing request [GET /chains/main/blocks/BLGKKX6ruC8GHGYrRb2UC3dbX4B216VPxBMXMsys3uCDzfwkcWZ/context/delegates/tz1LmaFsWRkjr7QMCx5PtV6xTUz3AmEpKQiF Empty] was dropped because pool is shutting down
[WARN] [03/10/2020 17:06:56.851] [lorre-system-akka.actor.default-dispatcher-16] [lorre-system/Pool(shared->http://192.168.56.103:8732)] [8 (WaitingForResponseEntitySubscription)] Ongoing request [GET /chains/main/blocks/BLGKKX6ruC8GHGYrRb2UC3dbX4B216VPxBMXMsys3uCDzfwkcWZ/context/delegates/tz1S8MNvuFEUsWgjHvi3AxibRBf388NhT1q2 Empty] was dropped because pool is shutting down
[WARN] [03/10/2020 17:06:56.851] [lorre-system-akka.actor.default-dispatcher-16] [lorre-system/Pool(shared->http://192.168.56.103:8732)] [10 (WaitingForResponseEntitySubscription)] Ongoing request [GET /chains/main/blocks/BLGKKX6ruC8GHGYrRb2UC3dbX4B216VPxBMXMsys3uCDzfwkcWZ/context/delegates/tz1LLNkQK4UQV6QcFShiXJ2vT2ELw449MzAA Empty] was dropped because pool is shutting down
[ERROR] [03/10/2020 17:06:56.884] [lorre-system-akka.actor.default-dispatcher-24] [akka.actor.ActorSystemImpl(lorre-system)] exception while executing timer task
java.lang.IllegalStateException: cannot create children while terminating or terminated
        at akka.actor.dungeon.Children.makeChild(Children.scala:273)
        at akka.actor.dungeon.Children.attachChild(Children.scala:49)
        at akka.actor.dungeon.Children.attachChild$(Children.scala:48)
        at akka.actor.ActorCell.attachChild(ActorCell.scala:429)
        at akka.actor.ActorSystemImpl.systemActorOf(ActorSystem.scala:750)
        at akka.stream.ActorMaterializer$.actorOfStreamSupervisor(ActorMaterializer.scala:73)
        at akka.stream.ActorMaterializer$.apply(ActorMaterializer.scala:65)
        at akka.stream.ActorMaterializer$.apply(ActorMaterializer.scala:42)
        at tech.cryptonomic.conseil.Lorre$.writeFutureRights(Lorre.scala:93)
        at tech.cryptonomic.conseil.Lorre$.$anonfun$new$3(Lorre.scala:84)
        at akka.actor.Scheduler$$anon$2.run(Scheduler.scala:102)
        at akka.actor.LightArrayRevolverScheduler$$anon$1$$anon$2.run(LightArrayRevolverScheduler.scala:101)
        at akka.actor.LightArrayRevolverScheduler$TaskHolder.run(LightArrayRevolverScheduler.scala:337)
        at akka.actor.LightArrayRevolverScheduler.$anonfun$close$1(LightArrayRevolverScheduler.scala:141)
        at akka.actor.LightArrayRevolverScheduler.$anonfun$close$1$adapted(LightArrayRevolverScheduler.scala:140)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at akka.actor.LightArrayRevolverScheduler.close(LightArrayRevolverScheduler.scala:140)
        at akka.actor.ActorSystemImpl.stopScheduler(ActorSystem.scala:937)
        at akka.actor.ActorSystemImpl.$anonfun$_start$1(ActorSystem.scala:872)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at akka.actor.ActorSystemImpl$$anon$3.run(ActorSystem.scala:892)
        at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$addRec$1$1.applyOrElse(ActorSystem.scala:1068)
        at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$addRec$1$1.applyOrElse(ActorSystem.scala:1068)
        at scala.concurrent.Future.$anonfun$andThen$1(Future.scala:536)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Exception in thread "main" 17:06:56.886 [main] INFO                                           tech.cryptonomic.conseil.Lorre$      - All things closed
tech.cryptonomic.conseil.tezos.TezosErrors$DelegatesProcessingFailed
        at tech.cryptonomic.conseil.Lorre$DelegatesProcessor$.$anonfun$process$39(Lorre.scala:743)
        at scala.concurrent.Future.$anonfun$transform$3(Future.scala:245)
        at scala.concurrent.Future.$anonfun$transform$1(Future.scala:245)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
17:06:56.898 [shutdownHook1] INFO                                  tech.cryptonomic.conseil.Lorre$      - Doing clean-up
Exception in thread "shutdownHook1" java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
        at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
        at scala.concurrent.Await$.$anonfun$result$1(package.scala:219)
        at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
        at scala.concurrent.Await$.result(package.scala:146)
        at tech.cryptonomic.conseil.Lorre$.shutdown(Lorre.scala:145)
        at tech.cryptonomic.conseil.Lorre$.$anonfun$new$2(Lorre.scala:70)
        at scala.sys.ShutdownHookThread$$anon$1.run(ShutdownHookThread.scala:37)
```

running command is 
``
nohup java -Dconfig.file=/home/docker/tezos/Conseil/test.conf -cp /tmp/conseil.jar tech.cryptonomic.conseil.Lorre --verbose mainnet 2>&1 > 02.lorre
``

test.conf file is below. 
```
include "metadata.conf"    
logger.scala.slick = DEBUG    
    
platforms: {    
  tezos: {    
    mainnet: {    
      node: {    
        protocol: "http"    
        hostname: "192.168.56.103",    
        port: 8732    
        pathPrefix: ""    
      }    
    }    
  }    
}    
    
conseil {    
  hostname: "192.168.56.103"    
  port: 11110    
  cache-ttl: 15 minutes    
  max-query-result-size: 100000    
    
  db {    
    dataSourceClass: "org.postgresql.ds.PGSimpleDataSource"  
    properties {    
      user: "postgres"    
      password: "test"    
      databaseName: "conseil"
      reWriteBatchedInserts: true
    }    
    numThreads: 20    
    maxConnections: 20    
  }    
    
  # Security settings    
  security.apiKeys {    
    # List of authorized API keys needed to query Conseil    
    keys: ["test01"]    
  }    
}    
    
lorre {    
  sleepInterval: 5 s    
  bootupRetryInterval: 10 s    
  bootupConnectionCheckTimeout: 10 s
  #Used to make sure Lorre records average fees every n iterations
  feeUpdateInterval: 20
  #Used to select how many fees should be averaged together
  numberOfFeesAveraged: 1000
  depth: newest,
  headHash: NONE

  requestAwaitTime: 120 s
  GETResponseEntityTimeout: 90 s
  POSTResponseEntityTimeout: 1 s 

  db {
    dataSourceClass: "org.postgresql.ds.PGSimpleDataSource"
    properties {
      user: "postgres"
      password: "test"
      reWriteBatchedInserts: true
      databaseName: "conseil"
    }
    numThreads: 20
    maxConnections: 20
  }

  batchedFetches {
    accountConcurrencyLevel: 5
    blockOperationsConcurrencyLevel: 10
    blockPageSize: 10
    blockPageProcessingTimeout: 15 minutes
    accountPageProcessingTimeout: 5
    delegatePageProcessingTimeout: 5 minutes
  }

  # Custom libSodium settings
  sodium.libraryPath: "/usr/lib/x86_64-linux-gnu/libsodium.so.18"
}

# Customization on the underlying actor system
# Customization on the underlying actor system
akka {
  tezos-streaming-client {
    max-connections: 30
    # The 2048 limit is thus overestimated by a factor of roughly 10x, to allow room for
    # reuse of the same pool from different threads at the same time, up to that factor
    max-open-requests: 2048
    # essentially keep connections alive across lorre's cycles
    idle-timeout: 10 minutes
    pipelining-limit: 7
    # give more room for async response in head-of-line blocking on the same connection or other slow responses
    response-entity-subscription-timeout: 5 seconds
  }
  tezos-dispatcher {
    type: "Dispatcher"
    executor: "thread-pool-executor"
    throughput: 1

    thread-pool-executor {
      fixed-pool-size: 16
    }
  }

  http {
    server {
      request-timeout: 5 minutes
      idle-timeout: 5 minutes
    }
  }
}
```

**Comment by ivanopagano** [comment]
First thing that comes to my mind is that delegates could be failing to download in a timely manner.

Can you try to raise the timeout value under the configuration entry
`akka.tezos-streaming-client.response-entity-subscription-timeout: 5 seconds`
to something like 15 seconds and see if that might, even temporarily, solve the issue?

**Comment by vishakh** [comment]
Closing as there was no follow up.
