### ISSUE TITLE
Can't build Conseil without docker

### ISSUE THREAD

**Issue by gituser** [Cryptonomic/Conseil#741]
Hi.

I'm trying to build latest release of Conseil `2020-march-release-21` with this build script:

```
#!/bin/bash
VERSION=$(git describe --tags)

# hack to build Conseil without docker

rm -f src/test/scala/tech/cryptonomic/conseil/tezos/ApiOperationsTest.scala
rm -f src/test/scala/tech/cryptonomic/conseil/tezos/TezosDatabaseOperationsTest.scala
rm -f src/test/scala/tech/cryptonomic/conseil/tezos/TezosPlatformDiscoveryOperationsTest.scala


sbt -J-Xss32m clean assembly
if [ "$?" != 0 ]; then
   echo "[-] Build failed!"
   exit 1
fi

mkdir -p ../conseil-$VERSION
cp -prv /tmp/conseil.jar  ../conseil-$VERSION/
rm ../conseil-current
ln -s conseil-$VERSION ../conseil-current
```

And failing with:

```
[info] - should convert a Ballot operation to a database row
[info] CsvConversionsTest:
[info] CSV conversions
[info] - should correctly convert List[QueryResponse] to CsvString
[info] - should correctly convert empty list
[info] BigMapOperationsTest:
[info] tech.cryptonomic.conseil.tezos.BigMapOperationsTest *** ABORTED ***
[info]   org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=postgres:11.6)
[info]   at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1153)
[info]   at org.testcontainers.containers.GenericContainer.setDockerImageName(GenericContainer.java:1141)
[info]   at org.testcontainers.containers.GenericContainer.<init>(GenericContainer.java:246)
[info]   at org.testcontainers.containers.JdbcDatabaseContainer.<init>(JdbcDatabaseContainer.java:36)
[info]   at org.testcontainers.containers.PostgreSQLContainer.<init>(PostgreSQLContainer.java:32)
[info]   at tech.cryptonomic.conseil.tezos.InMemoryDatabase.$init$(InMemoryDatabase.scala:19)
[info]   at tech.cryptonomic.conseil.tezos.BigMapOperationsTest.<init>(BigMapOperationsTest.scala:26)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   ...
[info]   Cause: java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
[info]   at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$3(DockerClientProviderStrategy.java:158)
[info]   at java.util.Optional.orElseThrow(Optional.java:290)
[info]   at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:150)
[info]   at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:111)
[info]   at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:51)
[info]   at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:27)
[info]   at org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:20)
[info]   at org.testcontainers.utility.LazyFuture.get(LazyFuture.java:27)
[info]   at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1151)
[info]   at org.testcontainers.containers.GenericContainer.setDockerImageName(GenericContainer.java:1141)
[info]   ...
[info] Run completed in 18 seconds, 520 milliseconds.
[info] Total number of tests run: 291
[info] Suites: completed 22, aborted 1
[info] Tests: succeeded 291, failed 0, canceled 0, ignored 0, pending 0
[info] *** 1 SUITE ABORTED ***
[error] Error during tests:
[error] 	tech.cryptonomic.conseil.tezos.BigMapOperationsTest
[error] (Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 70 s, completed Mar 26, 2020 12:58:22 PM
[-] Build failed!
```

Previous version of Conseil `conseil-2020-january-release-19` built just fine.

Can you please provide an ability to build Conseil without docker?

**Comment by ivanopagano** [comment]
Hi, try running the assembly [without the tests](https://stackoverflow.com/questions/26499444/how-run-sbt-assembly-command-without-tests-from-command-line)

**Comment by gituser** [comment]
@ivanopagano thanks for the quick reply, that worked.

For those who are having similar issue here is an updated `build.sh` script I'm using:
```
#!/bin/bash
VERSION=$(git describe --tags)

# hack to build Conseil without docker

#rm -f src/test/scala/tech/cryptonomic/conseil/tezos/ApiOperationsTest.scala
#rm -f src/test/scala/tech/cryptonomic/conseil/tezos/TezosDatabaseOperationsTest.scala
#rm -f src/test/scala/tech/cryptonomic/conseil/tezos/TezosPlatformDiscoveryOperationsTest.scala


sbt -J-Xss32m 'set test in assembly := {}' clean assembly
if [ "$?" != 0 ]; then
   echo "[-] Build failed!"
   exit 1
fi

mkdir -p ../conseil-$VERSION
cp -prv /tmp/conseil.jar  ../conseil-$VERSION/
rm ../conseil-current
ln -s conseil-$VERSION ../conseil-current
```

**Comment by ivanopagano** [comment]
Just for the record @gituser , since you skip the tests anyway, you need no more to remove manually the test files requiring docker.

Otherwise, you might want to keep running the tests and add the BigMapOperationsTest.scala, so your build will work again as before, even without the `set test in assembly`... stuff

**Comment by gituser** [comment]
@ivanopagano yes, I've reflected this since those lines are commented now.
