### ISSUE TITLE
"genSchema" role is broken when trying to update table schema

### ISSUE THREAD

**Issue by PrathamRawat** [Cryptonomic/Conseil#842]
Running `env SBT_OPTS="-Dconfig.file=conseil.conf" && sbt "genSchema"` as specified in the docs results in the following error:

```2020-06-10 10:57:34.513 EDT [6243] FATAL:  role "foo" does not exist
[error] (run-main-0) org.postgresql.util.PSQLException: FATAL: role "foo" does not exist
[error] org.postgresql.util.PSQLException: FATAL: role "foo" does not exist
[error]         at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
[error]         at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2559)
[error]         at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:133)
[error]         at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:250)
[error]         at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
[error]         at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
[error]         at org.postgresql.Driver.makeConnection(Driver.java:454)
[error]         at org.postgresql.Driver.connect(Driver.java:256)
[error]         at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[error]         at slick.jdbc.DataSourceJdbcDataSource.createConnection(JdbcDataSource.scala:68)
[error]         at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:494)
[error]         at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[error]         at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[error]         at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:250)
[error]         at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:249)
[error]         at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
[error]         at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:275)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] Nonzero exit code: 1
[error] (genSchema) Nonzero exit code: 1
[error] Total time: 166 s (02:46), completed Jun 10, 2020, 10:57:35 AM```

This should be fixed on both the r3 release brand and `master`

**Comment by ivanopagano** [comment]
it looks like the `conseil.conf` file used for the generation didn't include specific configuration for the local database connection.
The reference to a "foo" role hints that it's trying to connect with the default dummy parameters.

If you can confirm that a configuration change solves the issue, I'll close it @PrathamRawat 
Thanks

**Comment by PrathamRawat** [comment]
Indeed it does, thanks!

**Comment by ivanopagano** [comment]
Great
