### ISSUE TITLE
config for mainnet?

### ISSUE THREAD

**Issue by j4ys0n** [Cryptonomic/Conseil#975]
I'm having some trouble getting the indexer working with a full mainnet node. Running with mostly defaults for now until I can get this working - env vars for lorre are:
```
      CONSEIL_API_DB_URL: "jdbc:postgresql://conseil_postgres:5432/conseil-local"
      CONSEIL_API_DB_USER: "conseiluser"
      CONSEIL_API_DB_PASSWORD: "p@ssw0rd"
      CONSEIL_API_PORT: "80"
      CONSEIL_API_KEY: "conseil"
      CONSEIL_XTZ_NETWORK: "mainnet"
      CONSEIL_XTZ_ENABLED: "true"
      CONSEIL_XTZ_NODE_PROTOCOL: "http"
      CONSEIL_XTZ_NODE_HOSTNAME: "node-ip-here"
      CONSEIL_XTZ_NODE_PORT: "8732"
      JVM_XMX: "4G"
```

but i keep getting this error:

```
2021.03.29 04:41:18 [main] ERROR TezosIndexer    (tech.cryptonomic.conseil.indexer.tezos.TezosIndexer.checkTezosConnection:84) - Could not make initial connection to Tezos
io.circe.ParsingFailure: exhausted input
```

i've double checked that i am able to reach the xtz node from the lorre container, but lorre still will not connect. is there something missing?

**Comment by piotrkosecki** [comment]
Hi, my first guess is that you should set another env variable: `CONSEIL_XTZ_NODE_PATH_PREFIX: ""`.
I think in your case it should be an empty string.

**Comment by j4ys0n** [comment]
great! thank you. that got me past the error i was seeing - but now lorre can't decode the data for some reason. and then it shuts down. would the node version have anything to do with this? i'm on tezos v8.2
```
2021.03.29 14:50:57 [lorre-tezos-indexer-akka.actor.default-dispatcher-4] ERROR TezosNodeFetchers (tech.cryptonomic.conseil.indexer.tezos.TezosNodeFetchers.applyOrElse:40) - I fetched a block definition from tezos node that I'm unable to decode: {"protocol":"PtCJ7pwoxe8JasnHY8YonnLYjcVHmhiARPJvqcC6VfHT5s8k8sY","chain_id":"NetXdQprcVkpaWU","hash":"BM8m9eb1Zz4XgAXfkKiXfjxYq8aKEMgph2mLYrbfXLoQu3zPHoA","header":{"level":486,"proto":1,"predecessor":"BL3EpvXevfDUhchmZVKMTiZUYirZPoZjvq1JnUDwf3SD8iYUFzy","timestamp":"2018-07-01T01:48:42Z","validation_pass":4,"operations_hash":"LLoaYTcQvpyCZRb98VjPn4Yj2ZDHBiCtPPkbNZL6AXKsRx3CwTU9c","fitness":["00","0000000000003dd2"],"context":"CoVuGGU4D8jhYZpBLQeA5fQV5eMNM8P4r55MMwfn1yjMnMkqsmJ4","priority":0,"proof_of_work_nonce":"25589dee5ee54901","signature":"sigvntxUGgAyYyBx2J2ESvdamHvhTZvFGVyjJGbEjCXrTA69fZ6M1nxQXuu1GbKdvL2MEZ9bP1WQukcfwsTG8fyGeBAe6rwD"},"operations":[[{"protocol":"PtCJ7pwoxe8JasnHY8YonnLYjcVHmhiARPJvqcC6VfHT5s8k8sY","chain_id":"NetXdQprcVkpaWU","hash":"opXvyCBwj447qLF5uKzrXwu3qT4PVossadv5LQLN8NJD1YEJ5yU","branch":"BL3EpvXevfDUhchmZVKMTiZUYirZPoZjvq1JnUDwf3SD8iYUFzy","contents":[{"kind":"endorsement","level":485}],"signature":"sigjYqKpichTXwoYMuy1eF9KeissxWF4nGZ4VVjevSvBZg36AfCttTsxPXefLzFLX32hwTk7vVdmR1SvQTfaYg4mGtHYtDdC"},{"protocol":"PtCJ7pwoxe8JasnHY8YonnLYjcVHmhiARPJvqcC6VfHT5s8k8sY","chain_id":"NetXdQprcVkpaWU","hash":"ooUcGaCRPewf12pacJ9rkhu2nqzATvAiDBTZ2cP2qViJzgqUNCc","branch":"BL3EpvXevfDUhchmZVKMTiZUYirZPoZjvq1JnUDwf3SD8iYUFzy","contents":[{"kind":"endorsement","level":485}],"signature":"sigpeTJsFUQ1c9xw5bPffDH7EPKBbQ8QmZSTK2M8Z8xauFnF83XLntJbaRpumETjnz5ikf5NZAw4E2GrBHXJZFocN9Xh7SWg"},{"protocol":"PtCJ7pwoxe8JasnHY8YonnLYjcVHmhiARPJvqcC6VfHT5s8k8sY","chain_id":"NetXdQprcVkpaWU","hash":"onsGuf9d2qSXAngUeyAPbi1MMpVRwFKRbKdAEZmvf8Eik8WoD4d","branch":"BL3EpvXevfDUhchmZVKMTiZUYirZPoZjvq1JnUDwf3SD8iYUFzy","contents":[{"kind":"endorsement","level":485}],"signature":"sigT4uR9mwhjCgy1MRYf5ZyVp4cbTxGVpmg9cbppUEcmSHaBMprekhyT7gzus4y4kETKCpMhaXrKisaQmL3ThcxaE9Ss2wCE"},{"protocol":"PtCJ7pwoxe8JasnHY8YonnLYjcVHmhiARPJvqcC6VfHT5s8k8sY","chain_id":"NetXdQprcVkpaWU","hash":"ooCDAwAcvjq4pdfNKxPr3GVsQoz2dht4ggz5ZNQmwfijFYVYLUk","branch":"BL3EpvXevfDUhchmZVKMTiZUYirZPoZjvq1JnUDwf3SD8iYUFzy","contents":[{"kind":"endorsement","level":485}],"signature":"sigXiDZDraNhqjucNBVbS9c4t25u4EC9USFk2K5TxSeVqAFqzY8pZYAZ9kNhP9pQaNqPFZLcz6twTMdAPzd3rFN3sRs3kK18"},{"protocol":"PtCJ7pwoxe8JasnHY8YonnLYjcVHmhiARPJvqcC6VfHT5s8k8sY","chain_id":"NetXdQprcVkpaWU","hash":"opFL2WZSCnYLgzBSh6GpsyLM645XmtnMB1V3vZS4T7gvRSp3ei5","branch":"BL3EpvXevfDUhchmZVKMTiZUYirZPoZjvq1JnUDwf3SD8iYUFzy","contents":[{"kind":"endorsement","level":485}],"signature":"sigw19DgostAtBKtC1XoR9bd4NxDVm1aAQBvVhhXTpVGgSW5gdiW2E1PPzGBr12BUyj5nY3P6doGwGys856Bi4f4zK1mh1kb"},{"protocol":"PtCJ7pwoxe8JasnHY8YonnLYjcVHmhiARPJvqcC6VfHT5s8k8sY","chain_id":"NetXdQprcVkpaWU","hash":"ootupDmE5DPCTXFK67dBubQukd3wg7FbkKDUY8DVtbVaocDhwub","branch":"BL3EpvXevfDUhchmZVKMTiZUYirZPoZjvq1JnUDwf3SD8iYUFzy","contents":[{"kind":"endorsement","level":485}],"signature":"sigRTbkwvm8RaUsofZYumZPJMox1dqXMdFWxfYXq2pqkuZbPemB9NTP3CEyT944f27PEgzK1ErFB8mqseHhYiKcnh8iG8FdX"},{"protocol":"PtCJ7pwoxe8JasnHY8YonnLYjcVHmhiARPJvqcC6VfHT5s8k8sY","chain_id":"NetXdQprcVkpaWU","hash":"oniWsBpfC68v8CqH8yxXFjTCnvgyL7qunqdDKoLBWY3mZXi39Yu","branch":"BL3EpvXevfDUhchmZVKMTiZUYirZPoZjvq1JnUDwf3SD8iYUFzy","contents":[{"kind":"endorsement","level":485}],"signature":"sigRiVjarnaiEQDYUEq5hV7xXmKSmzic8VpmKVxZhbXtgNorXPQHu17anPnxW2rp1MUpC9neuZbDXBB7inDg3VZLk14uHLne"},{"protocol":"PtCJ7pwoxe8JasnHY8YonnLYjcVHmhiARPJvqcC6VfHT5s8k8sY","chain_id":"NetXdQprcVkpaWU","hash":"op9Luqj2TgVxiATXrC7Rqt9PNZwJcuHovyyY1jWPEkbhZdF5ihj","branch":"BL3EpvXevfDUhchmZVKMTiZUYirZPoZjvq1JnUDwf3SD8iYUFzy","contents":[{"kind":"endorsement","level":485}],"signature":"sigWnUvN8a9XTW8gRk9FqvcephgvVtzETAkKFPpYEZYxFwqaTp77Z7L9SxfhEzksoirX3YZvu8nMi8cevSfAEUh76kS9RhDZ"}],[],[{"protocol":"PtCJ7pwoxe8JasnHY8YonnLYjcVHmhiARPJvqcC6VfHT5s8k8sY","chain_id":"NetXdQprcVkpaWU","hash":"oooidFFzx3C6W4bDW8Y7xCkz9BxKiY8GtzChqe8y16ckJFttCoj","branch":"BL3EpvXevfDUhchmZVKMTiZUYirZPoZjvq1JnUDwf3SD8iYUFzy","contents":[{"kind":"activate_account","pkh":"tz1fbJkEmbNeeK7XcEZXgKbvbhZ1R8GHFrZ5","secret":"5341856bcdffd7ed7f2a57405dc016d98eefa088"}],"signature":"edsigtXomBKi5CTRf5cjATJWSyaRvhfYNHqSUGrn4SdbYRcGwQrUGjzEfQDTuqHhuA8b2d8NarZjz8TRf65WkpQmo423BtomS8Q"}],[]]}
io.circe.DecodingFailure$$anon$2: Attempt to decode value on failed cursor: DownField(metadata)


2021.03.29 14:50:57 [lorre-tezos-indexer-akka.actor.default-dispatcher-21] ERROR TezosIndexer    (tech.cryptonomic.conseil.indexer.tezos.TezosIndexer.processTezosBlocks:223) - Could not fetch blocks from client
io.circe.DecodingFailure$$anon$2: Attempt to decode value on failed cursor: DownField(metadata)


2021.03.29 14:50:57 [main] INFO  t.c.c.i.Lorre   (tech.cryptonomic.conseil.indexer.Lorre.shutdown:78) - Doing clean-up.

2021.03.29 14:50:57 [main] INFO  HikariDataSource (com.zaxxer.hikari.HikariDataSource) - lorre.db - Shutdown initiated...

2021.03.29 14:50:57 [main] INFO  HikariDataSource (com.zaxxer.hikari.HikariDataSource) - lorre.db - Shutdown completed.

Exception in thread "main" java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:220)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
	at scala.concurrent.Await$.result(package.scala:146)
	at tech.cryptonomic.conseil.indexer.Lorre$.shutdown(Lorre.scala:79)
	at tech.cryptonomic.conseil.indexer.Lorre$.delayedEndpoint$tech$cryptonomic$conseil$indexer$Lorre$1(Lorre.scala:75)
	at tech.cryptonomic.conseil.indexer.Lorre$delayedInit$body.apply(Lorre.scala:20)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at tech.cryptonomic.conseil.indexer.Lorre$.main(Lorre.scala:20)
	at tech.cryptonomic.conseil.indexer.Lorre.main(Lorre.scala)
2021.03.29 14:51:07 [shutdownHook1] INFO  t.c.c.i.Lorre   (tech.cryptonomic.conseil.indexer.Lorre.shutdown:78) - Doing clean-up.

Exception in thread "shutdownHook1" java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:220)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
	at scala.concurrent.Await$.result(package.scala:146)
	at tech.cryptonomic.conseil.indexer.Lorre$.shutdown(Lorre.scala:79)
	at tech.cryptonomic.conseil.indexer.Lorre$.$anonfun$new$2(Lorre.scala:44)
	at scala.sys.ShutdownHookThread$$anon$1.run(ShutdownHookThread.scala:37)
```

**Comment by piotrkosecki** [comment]
Are you running archive node?

**Comment by j4ys0n** [comment]
no, full node. should it be archive? if so, any idea how much disk space i need to allocate?

**Comment by piotrkosecki** [comment]
It has to be archive node. I think it should be around ~100 GB.

**Comment by j4ys0n** [comment]
got it - i'll get that going now. thank you!
